# Generated by Django 4.2.5 on 2023-09-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('linked_id', models.IntegerField(null=True)),
                ('link_precedence', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'unique_together': {('phone_number', 'email')},
            },
        ),
    ]
